// This file is auto-generated by @hey-api/openapi-ts

import {
	type Client,
	type Options as ClientOptions,
	type TDataShape,
	urlSearchParamsBodySerializer,
} from "./client/index.ts";
import { client as _heyApiClient } from "./client.gen.ts";
import type {
	AddDnsCustomARecordData,
	AddDnsCustomARecordErrors,
	AddDnsCustomARecordResponses,
	AddDnsCustomRecordData,
	AddDnsCustomRecordErrors,
	AddDnsCustomRecordResponses,
	AddDnsSecondaryNameserverData,
	AddDnsSecondaryNameserverErrors,
	AddDnsSecondaryNameserverResponses,
	AddMailUserData,
	AddMailUserErrors,
	AddMailUserPrivilegeData,
	AddMailUserPrivilegeErrors,
	AddMailUserPrivilegeResponses,
	AddMailUserResponses,
	GenerateSslcsrData,
	GenerateSslcsrErrors,
	GenerateSslcsrResponses,
	GetDnsCustomARecordsForQNameData,
	GetDnsCustomARecordsForQNameErrors,
	GetDnsCustomARecordsForQNameResponses,
	GetDnsCustomRecordsData,
	GetDnsCustomRecordsErrors,
	GetDnsCustomRecordsForQNameAndTypeData,
	GetDnsCustomRecordsForQNameAndTypeErrors,
	GetDnsCustomRecordsForQNameAndTypeResponses,
	GetDnsCustomRecordsResponses,
	GetDnsDumpData,
	GetDnsDumpErrors,
	GetDnsDumpResponses,
	GetDnsSecondaryNameserverData,
	GetDnsSecondaryNameserverErrors,
	GetDnsSecondaryNameserverResponses,
	GetDnsZonefileData,
	GetDnsZonefileErrors,
	GetDnsZonefileResponses,
	GetDnsZonesData,
	GetDnsZonesErrors,
	GetDnsZonesResponses,
	GetMailAliasesData,
	GetMailAliasesErrors,
	GetMailAliasesResponses,
	GetMailDomainsData,
	GetMailDomainsErrors,
	GetMailDomainsResponses,
	GetMailUserPrivilegesData,
	GetMailUserPrivilegesErrors,
	GetMailUserPrivilegesResponses,
	GetMailUsersData,
	GetMailUsersErrors,
	GetMailUsersResponses,
	GetSslStatusData,
	GetSslStatusErrors,
	GetSslStatusResponses,
	GetSystemBackupConfigData,
	GetSystemBackupConfigErrors,
	GetSystemBackupConfigResponses,
	GetSystemBackupStatusData,
	GetSystemBackupStatusErrors,
	GetSystemBackupStatusResponses,
	GetSystemPrivacyStatusData,
	GetSystemPrivacyStatusErrors,
	GetSystemPrivacyStatusResponses,
	GetSystemRebootStatusData,
	GetSystemRebootStatusErrors,
	GetSystemRebootStatusResponses,
	GetSystemStatusData,
	GetSystemStatusErrors,
	GetSystemStatusResponses,
	GetSystemUpdatesData,
	GetSystemUpdatesErrors,
	GetSystemUpdatesResponses,
	GetSystemUpstreamVersionData,
	GetSystemUpstreamVersionErrors,
	GetSystemUpstreamVersionResponses,
	GetSystemVersionData,
	GetSystemVersionErrors,
	GetSystemVersionResponses,
	GetWebDomainsData,
	GetWebDomainsErrors,
	GetWebDomainsResponses,
	InstallSslCertificateData,
	InstallSslCertificateErrors,
	InstallSslCertificateResponses,
	LoginData,
	LoginResponses,
	LogoutData,
	LogoutResponses,
	MfaStatusData,
	MfaStatusErrors,
	MfaStatusResponses,
	MfaTotpDisableData,
	MfaTotpDisableErrors,
	MfaTotpDisableResponses,
	MfaTotpEnableData,
	MfaTotpEnableErrors,
	MfaTotpEnableResponses,
	ProvisionSslCertificatesData,
	ProvisionSslCertificatesErrors,
	ProvisionSslCertificatesResponses,
	RebootSystemData,
	RebootSystemErrors,
	RebootSystemResponses,
	RemoveDnsCustomARecordData,
	RemoveDnsCustomARecordErrors,
	RemoveDnsCustomARecordResponses,
	RemoveDnsCustomRecordData,
	RemoveDnsCustomRecordErrors,
	RemoveDnsCustomRecordResponses,
	RemoveMailAliasData,
	RemoveMailAliasErrors,
	RemoveMailAliasResponses,
	RemoveMailUserData,
	RemoveMailUserErrors,
	RemoveMailUserPrivilegeData,
	RemoveMailUserPrivilegeErrors,
	RemoveMailUserPrivilegeResponses,
	RemoveMailUserResponses,
	SetMailUserPasswordData,
	SetMailUserPasswordErrors,
	SetMailUserPasswordResponses,
	UpdateDnsCustomARecordData,
	UpdateDnsCustomARecordErrors,
	UpdateDnsCustomARecordResponses,
	UpdateDnsCustomRecordData,
	UpdateDnsCustomRecordErrors,
	UpdateDnsCustomRecordResponses,
	UpdateDnsData,
	UpdateDnsErrors,
	UpdateDnsResponses,
	UpdateSystemBackupConfigData,
	UpdateSystemBackupConfigErrors,
	UpdateSystemBackupConfigResponses,
	UpdateSystemPackagesData,
	UpdateSystemPackagesErrors,
	UpdateSystemPackagesResponses,
	UpdateSystemPrivacyData,
	UpdateSystemPrivacyErrors,
	UpdateSystemPrivacyResponses,
	UpdateWebData,
	UpdateWebErrors,
	UpdateWebResponses,
	UpsertMailAliasData,
	UpsertMailAliasErrors,
	UpsertMailAliasResponses,
} from "./types.gen.ts";

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<
	TData,
	ThrowOnError
> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client;
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: Record<string, unknown>;
};

/**
 * Exchange a username and password for a session API key.
 * Returns user information and a session API key.
 *
 * Authenticate a user by supplying the auth token as a base64 encoded string in
 * format `email:password` using basic authentication headers.
 *
 * If successful, a long-lived `api_key` is returned which can be used for subsequent
 * requests to the API in place of the password.
 *
 */
export const login = <ThrowOnError extends boolean = false>(options?: Options<LoginData, ThrowOnError>) => {
	return (options?.client ?? _heyApiClient).post<LoginResponses, unknown, ThrowOnError>({
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/login",
		...options,
	});
};

/**
 * Invalidates a session API key.
 * Invalidates a session API key so that it cannot be used after this API call.
 *
 */
export const logout = <ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>) => {
	return (options?.client ?? _heyApiClient).post<LogoutResponses, unknown, ThrowOnError>({
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/logout",
		...options,
	});
};

/**
 * Get system status
 * Returns an array of statuses which can include headings.
 *
 */
export const getSystemStatus = <ThrowOnError extends boolean = false>(
	options?: Options<GetSystemStatusData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).post<GetSystemStatusResponses, GetSystemStatusErrors, ThrowOnError>({
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/system/status",
		...options,
	});
};

/**
 * Get system version
 * Returns installed Mail-in-a-Box version.
 */
export const getSystemVersion = <ThrowOnError extends boolean = false>(
	options?: Options<GetSystemVersionData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<GetSystemVersionResponses, GetSystemVersionErrors, ThrowOnError>({
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/system/version",
		...options,
	});
};

/**
 * Get system upstream version
 * Returns Mail-in-a-Box upstream version.
 */
export const getSystemUpstreamVersion = <ThrowOnError extends boolean = false>(
	options?: Options<GetSystemUpstreamVersionData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).post<
		GetSystemUpstreamVersionResponses,
		GetSystemUpstreamVersionErrors,
		ThrowOnError
	>({
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/system/latest-upstream-version",
		...options,
	});
};

/**
 * Get system updates
 * Returns system (apt) updates.
 */
export const getSystemUpdates = <ThrowOnError extends boolean = false>(
	options?: Options<GetSystemUpdatesData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<GetSystemUpdatesResponses, GetSystemUpdatesErrors, ThrowOnError>({
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/system/updates",
		...options,
	});
};

/**
 * Update system packages
 * Updates system (apt) packages.
 */
export const updateSystemPackages = <ThrowOnError extends boolean = false>(
	options?: Options<UpdateSystemPackagesData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).post<
		UpdateSystemPackagesResponses,
		UpdateSystemPackagesErrors,
		ThrowOnError
	>({
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/system/update-packages",
		...options,
	});
};

/**
 * Get system privacy status
 * Returns system privacy (new-version check) status.
 *
 * Response:
 *
 * - `true`: Private, new-version checks will not be performed
 * - `false`: Not private, new-version checks will be performed
 *
 */
export const getSystemPrivacyStatus = <ThrowOnError extends boolean = false>(
	options?: Options<GetSystemPrivacyStatusData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetSystemPrivacyStatusResponses,
		GetSystemPrivacyStatusErrors,
		ThrowOnError
	>({
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/system/privacy",
		...options,
	});
};

/**
 * Update system privacy
 * Updates system privacy (new-version checks).
 *
 * Request:
 *
 * - `value: private`: Disable new version checks
 * - `value: off`: Enable new version checks
 *
 */
export const updateSystemPrivacy = <ThrowOnError extends boolean = false>(
	options: Options<UpdateSystemPrivacyData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<UpdateSystemPrivacyResponses, UpdateSystemPrivacyErrors, ThrowOnError>({
		...urlSearchParamsBodySerializer,
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/system/privacy",
		...options,
		headers: {
			"Content-Type": "application/x-www-form-urlencoded",
			...options.headers,
		},
	});
};

/**
 * Get system reboot status
 * Returns the system reboot status.
 *
 * Response:
 *
 * - `true`: A reboot is required
 * - `false`: A reboot is not required
 *
 */
export const getSystemRebootStatus = <ThrowOnError extends boolean = false>(
	options?: Options<GetSystemRebootStatusData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetSystemRebootStatusResponses,
		GetSystemRebootStatusErrors,
		ThrowOnError
	>({
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/system/reboot",
		...options,
	});
};

/**
 * Reboot system
 * Reboots the system.
 */
export const rebootSystem = <ThrowOnError extends boolean = false>(
	options?: Options<RebootSystemData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).post<RebootSystemResponses, RebootSystemErrors, ThrowOnError>({
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/system/reboot",
		...options,
	});
};

/**
 * Get system backup status
 * Returns the system backup status.
 *
 * If the list of backups is empty, this implies no backups have been made yet.
 *
 */
export const getSystemBackupStatus = <ThrowOnError extends boolean = false>(
	options?: Options<GetSystemBackupStatusData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetSystemBackupStatusResponses,
		GetSystemBackupStatusErrors,
		ThrowOnError
	>({
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/system/backup/status",
		...options,
	});
};

/**
 * Get system backup config
 * Returns the system backup config.
 */
export const getSystemBackupConfig = <ThrowOnError extends boolean = false>(
	options?: Options<GetSystemBackupConfigData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetSystemBackupConfigResponses,
		GetSystemBackupConfigErrors,
		ThrowOnError
	>({
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/system/backup/config",
		...options,
	});
};

/**
 * Update system backup config
 * Updates the system backup config.
 */
export const updateSystemBackupConfig = <ThrowOnError extends boolean = false>(
	options: Options<UpdateSystemBackupConfigData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		UpdateSystemBackupConfigResponses,
		UpdateSystemBackupConfigErrors,
		ThrowOnError
	>({
		...urlSearchParamsBodySerializer,
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/system/backup/config",
		...options,
		headers: {
			"Content-Type": "application/x-www-form-urlencoded",
			...options.headers,
		},
	});
};

/**
 * Get SSL status
 * Returns the SSL status for all domains.
 */
export const getSslStatus = <ThrowOnError extends boolean = false>(
	options?: Options<GetSslStatusData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<GetSslStatusResponses, GetSslStatusErrors, ThrowOnError>({
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/ssl/status",
		...options,
	});
};

/**
 * Generate SSL CSR
 * Generates a Certificate Signing Request (CSR) for a domain & country code.
 *
 */
export const generateSslcsr = <ThrowOnError extends boolean = false>(
	options: Options<GenerateSslcsrData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<GenerateSslcsrResponses, GenerateSslcsrErrors, ThrowOnError>({
		...urlSearchParamsBodySerializer,
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/ssl/csr/{domain}",
		...options,
		headers: {
			"Content-Type": "application/x-www-form-urlencoded",
			...options.headers,
		},
	});
};

/**
 * Install SSL certificate
 * Installs a custom certificate. The chain certificate is optional.
 *
 */
export const installSslCertificate = <ThrowOnError extends boolean = false>(
	options: Options<InstallSslCertificateData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		InstallSslCertificateResponses,
		InstallSslCertificateErrors,
		ThrowOnError
	>({
		...urlSearchParamsBodySerializer,
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/ssl/install",
		...options,
		headers: {
			"Content-Type": "application/x-www-form-urlencoded",
			...options.headers,
		},
	});
};

/**
 * Provision SSL certificates
 * Provisions certificates for all domains.
 *
 */
export const provisionSslCertificates = <ThrowOnError extends boolean = false>(
	options?: Options<ProvisionSslCertificatesData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).post<
		ProvisionSslCertificatesResponses,
		ProvisionSslCertificatesErrors,
		ThrowOnError
	>({
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/ssl/provision",
		...options,
	});
};

/**
 * Get DNS secondary nameserver
 * Returns a list of nameserver hostnames.
 *
 */
export const getDnsSecondaryNameserver = <ThrowOnError extends boolean = false>(
	options?: Options<GetDnsSecondaryNameserverData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetDnsSecondaryNameserverResponses,
		GetDnsSecondaryNameserverErrors,
		ThrowOnError
	>({
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/dns/secondary-nameserver",
		...options,
	});
};

/**
 * Add DNS secondary nameserver
 * Adds one or more secondary nameservers.
 *
 */
export const addDnsSecondaryNameserver = <ThrowOnError extends boolean = false>(
	options: Options<AddDnsSecondaryNameserverData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		AddDnsSecondaryNameserverResponses,
		AddDnsSecondaryNameserverErrors,
		ThrowOnError
	>({
		...urlSearchParamsBodySerializer,
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/dns/secondary-nameserver",
		...options,
		headers: {
			"Content-Type": "application/x-www-form-urlencoded",
			...options.headers,
		},
	});
};

/**
 * Get DNS zones
 * Returns an array of all managed top-level domains.
 */
export const getDnsZones = <ThrowOnError extends boolean = false>(options?: Options<GetDnsZonesData, ThrowOnError>) => {
	return (options?.client ?? _heyApiClient).get<GetDnsZonesResponses, GetDnsZonesErrors, ThrowOnError>({
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/dns/zones",
		...options,
	});
};

/**
 * Get DNS zonefile
 * Returns a DNS zone file for a hostname.
 */
export const getDnsZonefile = <ThrowOnError extends boolean = false>(
	options: Options<GetDnsZonefileData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<GetDnsZonefileResponses, GetDnsZonefileErrors, ThrowOnError>({
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/dns/zonefile/{zone}",
		...options,
	});
};

/**
 * Update DNS
 * Updates the DNS. Involves creating zone files and restarting `nsd`.
 */
export const updateDns = <ThrowOnError extends boolean = false>(options: Options<UpdateDnsData, ThrowOnError>) => {
	return (options.client ?? _heyApiClient).post<UpdateDnsResponses, UpdateDnsErrors, ThrowOnError>({
		...urlSearchParamsBodySerializer,
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/dns/update",
		...options,
		headers: {
			"Content-Type": "application/x-www-form-urlencoded",
			...options.headers,
		},
	});
};

/**
 * Get DNS custom records
 * Returns all custom DNS records.
 */
export const getDnsCustomRecords = <ThrowOnError extends boolean = false>(
	options?: Options<GetDnsCustomRecordsData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<GetDnsCustomRecordsResponses, GetDnsCustomRecordsErrors, ThrowOnError>({
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/dns/custom",
		...options,
	});
};

/**
 * Remove DNS custom record
 * Removes a DNS custom record for the specified domain, type & value.
 */
export const removeDnsCustomRecord = <ThrowOnError extends boolean = false>(
	options: Options<RemoveDnsCustomRecordData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).delete<
		RemoveDnsCustomRecordResponses,
		RemoveDnsCustomRecordErrors,
		ThrowOnError
	>({
		bodySerializer: null,
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/dns/custom/{qname}/{rtype}",
		...options,
		headers: {
			"Content-Type": "text/plain",
			...options.headers,
		},
	});
};

/**
 * Get DNS custom records
 * Returns all custom records for the specified query name and type.
 */
export const getDnsCustomRecordsForQNameAndType = <ThrowOnError extends boolean = false>(
	options: Options<GetDnsCustomRecordsForQNameAndTypeData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetDnsCustomRecordsForQNameAndTypeResponses,
		GetDnsCustomRecordsForQNameAndTypeErrors,
		ThrowOnError
	>({
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/dns/custom/{qname}/{rtype}",
		...options,
	});
};

/**
 * Add DNS custom record
 * Adds a custom DNS record for the specified query name and type.
 */
export const addDnsCustomRecord = <ThrowOnError extends boolean = false>(
	options: Options<AddDnsCustomRecordData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<AddDnsCustomRecordResponses, AddDnsCustomRecordErrors, ThrowOnError>({
		bodySerializer: null,
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/dns/custom/{qname}/{rtype}",
		...options,
		headers: {
			"Content-Type": "text/plain",
			...options.headers,
		},
	});
};

/**
 * Update DNS custom record
 * Updates an existing DNS custom record value for the specified qname and type.
 */
export const updateDnsCustomRecord = <ThrowOnError extends boolean = false>(
	options: Options<UpdateDnsCustomRecordData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).put<
		UpdateDnsCustomRecordResponses,
		UpdateDnsCustomRecordErrors,
		ThrowOnError
	>({
		bodySerializer: null,
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/dns/custom/{qname}/{rtype}",
		...options,
		headers: {
			"Content-Type": "text/plain",
			...options.headers,
		},
	});
};

/**
 * Remove DNS custom A record
 * Removes a DNS custom A record for the specified domain & value.
 */
export const removeDnsCustomARecord = <ThrowOnError extends boolean = false>(
	options: Options<RemoveDnsCustomARecordData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).delete<
		RemoveDnsCustomARecordResponses,
		RemoveDnsCustomARecordErrors,
		ThrowOnError
	>({
		bodySerializer: null,
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/dns/custom/{qname}",
		...options,
		headers: {
			"Content-Type": "text/plain",
			...options.headers,
		},
	});
};

/**
 * Get DNS custom A records
 * Returns all custom A records for the specified query name.
 */
export const getDnsCustomARecordsForQName = <ThrowOnError extends boolean = false>(
	options: Options<GetDnsCustomARecordsForQNameData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetDnsCustomARecordsForQNameResponses,
		GetDnsCustomARecordsForQNameErrors,
		ThrowOnError
	>({
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/dns/custom/{qname}",
		...options,
	});
};

/**
 * Add DNS custom A record
 * Adds a custom DNS A record for the specified query name.
 */
export const addDnsCustomARecord = <ThrowOnError extends boolean = false>(
	options: Options<AddDnsCustomARecordData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<AddDnsCustomARecordResponses, AddDnsCustomARecordErrors, ThrowOnError>({
		bodySerializer: null,
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/dns/custom/{qname}",
		...options,
		headers: {
			"Content-Type": "text/plain",
			...options.headers,
		},
	});
};

/**
 * Update DNS custom A record
 * Updates an existing DNS custom A record value for the specified qname.
 */
export const updateDnsCustomARecord = <ThrowOnError extends boolean = false>(
	options: Options<UpdateDnsCustomARecordData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).put<
		UpdateDnsCustomARecordResponses,
		UpdateDnsCustomARecordErrors,
		ThrowOnError
	>({
		bodySerializer: null,
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/dns/custom/{qname}",
		...options,
		headers: {
			"Content-Type": "text/plain",
			...options.headers,
		},
	});
};

/**
 * Get DNS dump
 * Returns all DNS records.
 */
export const getDnsDump = <ThrowOnError extends boolean = false>(options?: Options<GetDnsDumpData, ThrowOnError>) => {
	return (options?.client ?? _heyApiClient).get<GetDnsDumpResponses, GetDnsDumpErrors, ThrowOnError>({
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/dns/dump",
		...options,
	});
};

/**
 * Get mail users
 * Returns all mail users.
 */
export const getMailUsers = <ThrowOnError extends boolean = false>(
	options?: Options<GetMailUsersData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<GetMailUsersResponses, GetMailUsersErrors, ThrowOnError>({
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/mail/users",
		...options,
	});
};

/**
 * Add mail user
 * Adds a new mail user.
 */
export const addMailUser = <ThrowOnError extends boolean = false>(options: Options<AddMailUserData, ThrowOnError>) => {
	return (options.client ?? _heyApiClient).post<AddMailUserResponses, AddMailUserErrors, ThrowOnError>({
		...urlSearchParamsBodySerializer,
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/mail/users/add",
		...options,
		headers: {
			"Content-Type": "application/x-www-form-urlencoded",
			...options.headers,
		},
	});
};

/**
 * Remove mail user
 * Removes an existing mail user.
 */
export const removeMailUser = <ThrowOnError extends boolean = false>(
	options: Options<RemoveMailUserData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<RemoveMailUserResponses, RemoveMailUserErrors, ThrowOnError>({
		...urlSearchParamsBodySerializer,
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/mail/users/remove",
		...options,
		headers: {
			"Content-Type": "application/x-www-form-urlencoded",
			...options.headers,
		},
	});
};

/**
 * Add mail user privilege
 * Adds a privilege to an existing mail user.
 */
export const addMailUserPrivilege = <ThrowOnError extends boolean = false>(
	options: Options<AddMailUserPrivilegeData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		AddMailUserPrivilegeResponses,
		AddMailUserPrivilegeErrors,
		ThrowOnError
	>({
		...urlSearchParamsBodySerializer,
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/mail/users/privileges/add",
		...options,
		headers: {
			"Content-Type": "application/x-www-form-urlencoded",
			...options.headers,
		},
	});
};

/**
 * Remove mail user privilege
 * Removes a privilege from an existing mail user.
 */
export const removeMailUserPrivilege = <ThrowOnError extends boolean = false>(
	options: Options<RemoveMailUserPrivilegeData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		RemoveMailUserPrivilegeResponses,
		RemoveMailUserPrivilegeErrors,
		ThrowOnError
	>({
		...urlSearchParamsBodySerializer,
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/mail/users/privileges/remove",
		...options,
		headers: {
			"Content-Type": "application/x-www-form-urlencoded",
			...options.headers,
		},
	});
};

/**
 * Set mail user password
 * Sets a password for an existing mail user.
 */
export const setMailUserPassword = <ThrowOnError extends boolean = false>(
	options: Options<SetMailUserPasswordData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<SetMailUserPasswordResponses, SetMailUserPasswordErrors, ThrowOnError>({
		...urlSearchParamsBodySerializer,
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/mail/users/password",
		...options,
		headers: {
			"Content-Type": "application/x-www-form-urlencoded",
			...options.headers,
		},
	});
};

/**
 * Get mail user privileges
 * Returns all privileges for an existing mail user.
 */
export const getMailUserPrivileges = <ThrowOnError extends boolean = false>(
	options?: Options<GetMailUserPrivilegesData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetMailUserPrivilegesResponses,
		GetMailUserPrivilegesErrors,
		ThrowOnError
	>({
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/mail/users/privileges",
		...options,
	});
};

/**
 * Get mail domains
 * Returns all mail domains.
 */
export const getMailDomains = <ThrowOnError extends boolean = false>(
	options?: Options<GetMailDomainsData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<GetMailDomainsResponses, GetMailDomainsErrors, ThrowOnError>({
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/mail/domains",
		...options,
	});
};

/**
 * Get mail aliases
 * Returns all mail aliases.
 */
export const getMailAliases = <ThrowOnError extends boolean = false>(
	options?: Options<GetMailAliasesData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<GetMailAliasesResponses, GetMailAliasesErrors, ThrowOnError>({
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/mail/aliases",
		...options,
	});
};

/**
 * Upsert mail alias
 * Adds or updates a mail alias. If updating, you need to set `update_if_exists: 1`.
 *
 */
export const upsertMailAlias = <ThrowOnError extends boolean = false>(
	options: Options<UpsertMailAliasData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<UpsertMailAliasResponses, UpsertMailAliasErrors, ThrowOnError>({
		...urlSearchParamsBodySerializer,
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/mail/aliases/add",
		...options,
		headers: {
			"Content-Type": "application/x-www-form-urlencoded",
			...options.headers,
		},
	});
};

/**
 * Remove mail alias
 * Removes a mail alias.
 */
export const removeMailAlias = <ThrowOnError extends boolean = false>(
	options: Options<RemoveMailAliasData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<RemoveMailAliasResponses, RemoveMailAliasErrors, ThrowOnError>({
		...urlSearchParamsBodySerializer,
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/mail/aliases/remove",
		...options,
		headers: {
			"Content-Type": "application/x-www-form-urlencoded",
			...options.headers,
		},
	});
};

/**
 * Get web domains
 * Returns all static web domains.
 */
export const getWebDomains = <ThrowOnError extends boolean = false>(
	options?: Options<GetWebDomainsData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<GetWebDomainsResponses, GetWebDomainsErrors, ThrowOnError>({
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/web/domains",
		...options,
	});
};

/**
 * Update web
 * Updates static websites, used for updating domain root directories.
 */
export const updateWeb = <ThrowOnError extends boolean = false>(options?: Options<UpdateWebData, ThrowOnError>) => {
	return (options?.client ?? _heyApiClient).post<UpdateWebResponses, UpdateWebErrors, ThrowOnError>({
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/web/update",
		...options,
	});
};

/**
 * Retrieve MFA status for you or another user
 * Retrieves which type of MFA is used and configuration
 */
export const mfaStatus = <ThrowOnError extends boolean = false>(options?: Options<MfaStatusData, ThrowOnError>) => {
	return (options?.client ?? _heyApiClient).post<MfaStatusResponses, MfaStatusErrors, ThrowOnError>({
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/mfa/status",
		...options,
	});
};

/**
 * Enable TOTP authentication
 * Enables TOTP authentication for the currently logged-in admin user
 */
export const mfaTotpEnable = <ThrowOnError extends boolean = false>(
	options: Options<MfaTotpEnableData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<MfaTotpEnableResponses, MfaTotpEnableErrors, ThrowOnError>({
		...urlSearchParamsBodySerializer,
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/mfa/totp/enable",
		...options,
		headers: {
			"Content-Type": "application/x-www-form-urlencoded",
			...options.headers,
		},
	});
};

/**
 * Disable multi-factor authentication for you or another user
 * Disables multi-factor authentication for the currently logged-in admin user or another user if a 'user' parameter is submitted. Either disables all multi-factor authentication methods or the method corresponding to the optional property `mfa_id`.
 */
export const mfaTotpDisable = <ThrowOnError extends boolean = false>(
	options?: Options<MfaTotpDisableData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).post<MfaTotpDisableResponses, MfaTotpDisableErrors, ThrowOnError>({
		...urlSearchParamsBodySerializer,
		security: [
			{
				scheme: "basic",
				type: "http",
			},
		],
		url: "/mfa/disable",
		...options,
		headers: {
			"Content-Type": "application/x-www-form-urlencoded",
			...options?.headers,
		},
	});
};
